-- Migration: 20260421_01_backfill_undocumented_columns
-- Safe to re-run: yes (IF NOT EXISTS / idempotent TYPE casts throughout)
-- Applied: 2026-04-21
-- Description: Document columns that exist in Neon DB but were never captured in
--   migration files. All ADD COLUMNs are IF NOT EXISTS (no-op if already present).
--   Adds COMMENT ON for all previously uncommented columns.

-- ── exercise_sessions ────────────────────────────────────────────────────────

ALTER TABLE exercise_sessions
  ADD COLUMN IF NOT EXISTS hr_avg      INT,
  ADD COLUMN IF NOT EXISTS effort      INT,
  ADD COLUMN IF NOT EXISTS distance_mi NUMERIC;

COMMENT ON COLUMN exercise_sessions.hr_avg      IS 'Average heart rate in bpm during the session.';
COMMENT ON COLUMN exercise_sessions.effort      IS 'Self-reported effort rating 1–10 (1=very easy, 10=maximal).';
COMMENT ON COLUMN exercise_sessions.distance_mi IS 'Distance in miles. Populated for Run, Walk, and Cycling sessions.';
COMMENT ON COLUMN exercise_sessions.cadence_spm IS 'Running cadence in strides per minute. Only populated for Run sessions.';

-- ── entries ───────────────────────────────────────────────────────────────────

ALTER TABLE entries
  ADD COLUMN IF NOT EXISTS weekday       TEXT,
  ADD COLUMN IF NOT EXISTS timezone      TEXT,
  ADD COLUMN IF NOT EXISTS alcohol_count INT,
  ADD COLUMN IF NOT EXISTS alcohol_desc  TEXT;

-- hrv was INT in the initial schema; Neon reflects it as NUMERIC — align them.
ALTER TABLE entries
  ALTER COLUMN hrv TYPE NUMERIC;

COMMENT ON COLUMN entries.weekday       IS 'Day of week derived from date (e.g. Monday). Stored for convenient querying.';
COMMENT ON COLUMN entries.timezone      IS 'IANA timezone of the log entry (e.g. America/New_York). Sourced from Spine Log.';
COMMENT ON COLUMN entries.alcohol_count IS 'Number of alcoholic drinks consumed.';
COMMENT ON COLUMN entries.alcohol_desc  IS 'Free-text description of alcohol consumed (e.g. "2 beers, 1 glass wine").';

-- ── reports ───────────────────────────────────────────────────────────────────

ALTER TABLE reports
  ADD COLUMN IF NOT EXISTS report_date   DATE,
  ADD COLUMN IF NOT EXISTS period_start  DATE,
  ADD COLUMN IF NOT EXISTS period_end    DATE,
  ADD COLUMN IF NOT EXISTS model         TEXT,
  ADD COLUMN IF NOT EXISTS input_tokens  INT,
  ADD COLUMN IF NOT EXISTS output_tokens INT;

COMMENT ON COLUMN reports.report_date   IS 'Date this report was generated (calendar date, not timestamp).';
COMMENT ON COLUMN reports.period_start  IS 'Start date of the period covered by this report.';
COMMENT ON COLUMN reports.period_end    IS 'End date of the period covered by this report.';
COMMENT ON COLUMN reports.model         IS 'AI model used to generate the report (e.g. gpt-4o-mini).';
COMMENT ON COLUMN reports.input_tokens  IS 'Number of input tokens consumed by the model for this report.';
COMMENT ON COLUMN reports.output_tokens IS 'Number of output tokens generated by the model for this report.';
