-- Current state of the reports table.
-- One row per weekly AI-generated synthesis report.
-- Update this file whenever a migration changes this table.

CREATE TABLE IF NOT EXISTS reports (
  id            SERIAL PRIMARY KEY,
  week_start    DATE,
  content       TEXT,
  generated_at  TIMESTAMP
);

COMMENT ON TABLE reports IS 'One row per weekly AI-generated synthesis report. Produced every Monday by the GitHub Actions workflow using GitHub Models (gpt-4o-mini) against the prior 7 days of entries.';

COMMENT ON COLUMN reports.id           IS 'Auto-incrementing primary key.';
COMMENT ON COLUMN reports.week_start   IS 'Start date of the analyzed week.';
COMMENT ON COLUMN reports.content      IS 'Full markdown synthesis text as generated by the AI model.';
COMMENT ON COLUMN reports.generated_at IS 'Timestamp when the report was generated.';
