-- Current state of the reports table.
-- One row per AI-generated synthesis report.
-- Update this file whenever a migration changes this table.

CREATE TABLE IF NOT EXISTS reports (
  id             SERIAL PRIMARY KEY,
  report_date    DATE         NOT NULL,
  period_start   DATE         NOT NULL,
  period_end     DATE         NOT NULL,
  content        TEXT         NOT NULL,
  model          TEXT,
  input_tokens   INT,
  output_tokens  INT,
  generated_at   TIMESTAMP WITH TIME ZONE
);

COMMENT ON TABLE reports IS 'One row per AI-generated synthesis report. Covers a date range (period_start–period_end); typically weekly, produced by a GitHub Actions workflow.';

COMMENT ON COLUMN reports.id             IS 'Auto-incrementing primary key.';
COMMENT ON COLUMN reports.report_date    IS 'Date this report was generated (calendar date, not timestamp).';
COMMENT ON COLUMN reports.period_start   IS 'Start date of the period covered by this report.';
COMMENT ON COLUMN reports.period_end     IS 'End date of the period covered by this report.';
COMMENT ON COLUMN reports.content        IS 'Full markdown synthesis text as generated by the AI model.';
COMMENT ON COLUMN reports.model          IS 'AI model used to generate the report (e.g. gpt-4o-mini).';
COMMENT ON COLUMN reports.input_tokens   IS 'Number of input tokens consumed by the model for this report.';
COMMENT ON COLUMN reports.output_tokens  IS 'Number of output tokens generated by the model for this report.';
COMMENT ON COLUMN reports.generated_at   IS 'Timestamp when the report was generated.';
